language: java
sudo: false

before_install:
  - unset TRAVIS
  - unset _JAVA_OPTIONS
  - wget http://www.deflaker.org/maven/apache-maven-3.5.0.zip
  - unzip -qq apache-maven-3.5.0.zip
  - export M2_HOME=$PWD/apache-maven-3.5.0
  - export PATH=$M2_HOME/bin:$PATH

env:
  - FIREBASE_KEY=AIzaSyDU7I6pnN322BvRNN24jRX52owAvuHH1K4

install: true
script: mvn verify -B

jdk:
  - openjdk8
#   - openjdk9
#   - openjdk10
#   - openjdk11
